@Users.API_HostAddress = http://localhost:5100

GET {{Users.API_HostAddress}}/
Accept: application/json

###

POST {{Users.API_HostAddress}}
Content-Type: application/json

{
  "NewUser":{
      "email" : "test@test.test"
  }
}
